### ISSUE TITLE
Show most recent tasks on main page

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/contractwork#15]
A "most recent tasks" list across all workers would be useful. Currently a full task list is only shown for each worker on their `worker.php` page. Maybe show just the most recent 100 or something. I wanted to link to this to give people an idea of where we do work these days (since we aren't on WP).

**Comment by vipulnaik** [comment]
topicTaskList for an empty topic works to give the full list of tasks:

https://contractwork.vipulnaik.com/topic.php#topicTaskList

Does that work for your purpose :)?

**Comment by riceissa** [comment]
That does work for me. I guess I'll close this.
