### ISSUE TITLE
Payments due by worker and year

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/contractwork#16]
A "payments due by worker and year" table on the main page, similar to the other ones on the page, would be useful. I wanted to see which workers have been active in 2017, and currently there is no way to check this without going to each worker's page.

**Comment by riceissa** [comment]
Two clarifications:

* doing only task payments is fine, rather than doing all payments
* having a similar monthly table, as with the other groupings, would also be useful

**Comment by vipulnaik** [comment]
Done. If it works for you, fft close the issue :).

**Comment by riceissa** [comment]
Thanks, looks great :heart_eyes_cat:
