### ISSUE TITLE
Link to EIC calculator in tax advice

### ISSUE THREAD

**Issue by riceissa** [vipulnaik/contractwork#27]
please link to https://apps.irs.gov/app/eitc and say it is for the main form 1040 line 27

probably right above the paragraph that starts with "If you have made estimated tax payments (using Form 1040-ES by mail or through EFTPS) or if you chose a credit elect last year, you need to enter the total amount applied from last year plus your estimated tax payments on line 26."

**Comment by vipulnaik** [comment]
I ended up putting a note both at the beginning and just *below* the instruction for line 26, rather than above. I'm going to close now but let me know if you have any feedback @riceissa.

**Comment by riceissa** [comment]
Thanks! The way I used the EITC calculator (that made more sense to me) is that the EITC calculator is trying to find your AGI, and by that point in filing your tax return, you already know your AGI, so you should turn whatever knobs (as part of the calculator's form) are necessary so that the AGI at the bottom of the calculator matches the AGI line in the tax return.
